# Generated by Django 5.1.3 on 2025-04-09 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('creativity_tasks', models.PositiveIntegerField(default=0)),
                ('strength_tasks', models.PositiveIntegerField(default=0)),
                ('intelligence_tasks', models.PositiveIntegerField(default=0)),
                ('weekly_tasks', models.PositiveIntegerField(default=0)),
                ('monday_tasks', models.PositiveIntegerField(default=0)),
                ('tuesday_tasks', models.PositiveIntegerField(default=0)),
                ('wednesday_tasks', models.PositiveIntegerField(default=0)),
                ('thursday_tasks', models.PositiveIntegerField(default=0)),
                ('friday_tasks', models.PositiveIntegerField(default=0)),
                ('saturday_tasks', models.PositiveIntegerField(default=0)),
                ('sunday_tasks', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Statistics',
                'verbose_name_plural': 'User Statistics',
            },
        ),
    ]
