# Generated by Django 5.1.3 on 2025-04-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longtask',
            name='due_date',
        ),
    ]
